name: Bug Report
description: Report an issue with Laravel TypeScript
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to report a bug! Please fill in the details below to help us resolve it.
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Describe the problem and what you expected to happen.
          placeholder: When I run `php artisan typescript:generate`, the output is missing...
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to reproduce the bug
          description: Provide steps to reproduce, include your model code and config values if relevant.
          placeholder: |
              1. Created a model with enum cast
              2. Ran `php artisan typescript:generate`
              3. The enum type was not generated
      validations:
          required: true
    - type: textarea
      id: expected-output
      attributes:
          label: Expected TypeScript output
          description: Paste the TypeScript you expected to be generated (if applicable).
          placeholder: |
              export interface User {
                role: UserRole;
              }
      validations:
          required: false
    - type: textarea
      id: actual-output
      attributes:
          label: Actual TypeScript output
          description: Paste the TypeScript that was actually generated (if applicable).
      validations:
          required: false
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: What version of `frolaxhq/laravel-typescript` are you running?
          placeholder: 1.0.0
      validations:
          required: true
    - type: input
      id: php-version
      attributes:
          label: PHP Version
          placeholder: 8.4.0
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
        label: Laravel Version
        placeholder: 12.0.0
      validations:
        required: true
    - type: dropdown
      id: database-driver
      attributes:
        label: Database driver
        description: Which database driver are you using?
        options:
        - MySQL / MariaDB
        - PostgreSQL
        - SQLite
        - SQL Server
        - MongoDB
        - Other
    - type: dropdown
      id: operating-systems
      attributes:
        label: Which operating systems does this happen with?
        multiple: true
        options:
        - macOS
        - Windows
        - Linux
    - type: textarea
      id: notes
      attributes:
          label: Additional context
          description: Any other details, config, or screenshots that might help.
      validations:
          required: false
